//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BohaWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BohaWpf.Properties.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The book &quot;&lt;BOOKNAME&gt;&quot; and all its data will be deleted. Continue? ähnelt.
        /// </summary>
        public static string ChooseBookView_DeleteConfirmText {
            get {
                return ResourceManager.GetString("ChooseBookView_DeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string ChooseBookView_AddNewBook_Content {
            get {
                return ResourceManager.GetString("ChooseBookView_AddNewBook_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add New Book ähnelt.
        /// </summary>
        public static string ChooseBookView_AddNewBook_ToolTip {
            get {
                return ResourceManager.GetString("ChooseBookView_AddNewBook_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string ChooseBookView_ChooseBookButton_Content {
            get {
                return ResourceManager.GetString("ChooseBookView_ChooseBookButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string ChooseBookView_DeleteBookButton_Content {
            get {
                return ResourceManager.GetString("ChooseBookView_DeleteBookButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Book ähnelt.
        /// </summary>
        public static string ChooseBookView_DeleteBookButton_ToolTip {
            get {
                return ResourceManager.GetString("ChooseBookView_DeleteBookButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Book ähnelt.
        /// </summary>
        public static string ChooseBookView_NewBookLabel_Text {
            get {
                return ResourceManager.GetString("ChooseBookView_NewBookLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Book ähnelt.
        /// </summary>
        public static string ChooseBookView_Title {
            get {
                return ResourceManager.GetString("ChooseBookView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ChooseMonthView_CancelButton_Content {
            get {
                return ResourceManager.GetString("ChooseMonthView_CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string ChooseMonthView_OkButton_Content {
            get {
                return ResourceManager.GetString("ChooseMonthView_OkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Month ähnelt.
        /// </summary>
        public static string ChooseMonthView_Title {
            get {
                return ResourceManager.GetString("ChooseMonthView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string ConfirmView_Title {
            get {
                return ResourceManager.GetString("ConfirmView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string ConfirmWindowTitle {
            get {
                return ResourceManager.GetString("ConfirmWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string EditCategoriesView_AddCategoryButton_Content {
            get {
                return ResourceManager.GetString("EditCategoriesView_AddCategoryButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Category ähnelt.
        /// </summary>
        public static string EditCategoriesView_AddCategoryButton_ToolTip {
            get {
                return ResourceManager.GetString("EditCategoriesView_AddCategoryButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string EditCategoriesView_DeleteCategoryButton_Content {
            get {
                return ResourceManager.GetString("EditCategoriesView_DeleteCategoryButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Category ähnelt.
        /// </summary>
        public static string EditCategoriesView_DeleteCategoryButton_ToolTip {
            get {
                return ResourceManager.GetString("EditCategoriesView_DeleteCategoryButton_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The category &quot;&lt;CATEGORYE&gt;&quot; of the book &quot;&lt;BOOKNAMEE&gt;&quot; will be removed. Continue? ähnelt.
        /// </summary>
        public static string EditCategoriesView_DeleteConfirmText
        {
            get
            {
                return ResourceManager.GetString("EditCategoriesView_DeleteConfirmText", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Category ähnelt.
        /// </summary>
        public static string EditCategoriesView_NewCategoryLabel_Text {
            get {
                return ResourceManager.GetString("EditCategoriesView_NewCategoryLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Categories ähnelt.
        /// </summary>
        public static string EditCategoriesView_Title {
            get {
                return ResourceManager.GetString("EditCategoriesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string General_NoButton_Content {
            get {
                return ResourceManager.GetString("General_NoButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string General_YesButton_Content {
            get {
                return ResourceManager.GetString("General_YesButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string MainView_AmountLabel_Text {
            get {
                return ResourceManager.GetString("MainView_AmountLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M ähnelt.
        /// </summary>
        public static string MainView_ChangeMonthButton_Content {
            get {
                return ResourceManager.GetString("MainView_ChangeMonthButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Month ähnelt.
        /// </summary>
        public static string MainView_ChangeMonthButton_ToolTip {
            get {
                return ResourceManager.GetString("MainView_ChangeMonthButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        public static string MainView_ChooseBookButton_Content {
            get {
                return ResourceManager.GetString("MainView_ChooseBookButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Book ähnelt.
        /// </summary>
        public static string MainView_ChooseBookButton_ToolTip {
            get {
                return ResourceManager.GetString("MainView_ChooseBookButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Entry ähnelt.
        /// </summary>
        public static string MainView_CreateEntryButton_Content {
            get {
                return ResourceManager.GetString("MainView_CreateEntryButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string MainView_DefaultBookName {
            get {
                return ResourceManager.GetString("MainView_DefaultBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die D ähnelt.
        /// </summary>
        public static string MainView_DeleteEntryButton_Content {
            get {
                return ResourceManager.GetString("MainView_DeleteEntryButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Entry ähnelt.
        /// </summary>
        public static string MainView_DeleteEntryButton_ToolTip {
            get {
                return ResourceManager.GetString("MainView_DeleteEntryButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E ähnelt.
        /// </summary>
        public static string MainView_EditCategoriesButton_Content {
            get {
                return ResourceManager.GetString("MainView_EditCategoriesButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Categories ähnelt.
        /// </summary>
        public static string MainView_EditCategoriesButton_ToolTip {
            get {
                return ResourceManager.GetString("MainView_EditCategoriesButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string MainView_EntriesDataGrid_Header_Amount {
            get {
                return ResourceManager.GetString("MainView_EntriesDataGrid_Header_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string MainView_EntriesDataGrid_Header_Category {
            get {
                return ResourceManager.GetString("MainView_EntriesDataGrid_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string MainView_EntriesDataGrid_Header_Date {
            get {
                return ResourceManager.GetString("MainView_EntriesDataGrid_Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo ähnelt.
        /// </summary>
        public static string MainView_EntriesDataGrid_Header_MemoText {
            get {
                return ResourceManager.GetString("MainView_EntriesDataGrid_Header_MemoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deposit ähnelt.
        /// </summary>
        public static string MainView_EntryTypes_Deposit {
            get {
                return ResourceManager.GetString("MainView_EntryTypes_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payout ähnelt.
        /// </summary>
        public static string MainView_EntryTypes_Payout {
            get {
                return ResourceManager.GetString("MainView_EntryTypes_Payout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memo Text ähnelt.
        /// </summary>
        public static string MainView_MemoTextLabel_Text {
            get {
                return ResourceManager.GetString("MainView_MemoTextLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &gt; ähnelt.
        /// </summary>
        public static string MainView_NextMonthButton_Content {
            get {
                return ResourceManager.GetString("MainView_NextMonthButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Month ähnelt.
        /// </summary>
        public static string MainView_NextMonthButton_ToolTip {
            get {
                return ResourceManager.GetString("MainView_NextMonthButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; ähnelt.
        /// </summary>
        public static string MainView_PreviousMonthButton_Content {
            get {
                return ResourceManager.GetString("MainView_PreviousMonthButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Month ähnelt.
        /// </summary>
        public static string MainView_PreviousMonthButton_ToolTip {
            get {
                return ResourceManager.GetString("MainView_PreviousMonthButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BOHA - Book Of Household Accounts ähnelt.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
    }
}
